### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[479, 444, 5, 216], [479, 444, 5, 34], [479, 300, 5, 160], [48, 143, 415, 130, 182], [48, 143, 415, 130, 418], [260, 479, 445, 5, 215], [270, 326, 406, 130]]


### Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 479 444   5 216]
 [  0   0   0   0 479 444   5  34]
 [  0   0   0   0 479 300   5 160]
 [  0   0   0  48 143 415 130 182]
 [  0   0   0  48 143 415 130 418]
 [  0   0   0 260 479 445   5 215]
 [  0   0   0   0 270 326 406 130]]


In [ ]:
## 10 feature dimesnions
dim=10


In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 479, 444,   5, 216], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 98ms/step


array([[ 0.04953771,  0.0288942 , -0.0360706 ,  0.03609833, -0.03908775,
         0.01265476,  0.00910169, -0.01391762,  0.01885051,  0.01318571],
       [ 0.04953771,  0.0288942 , -0.0360706 ,  0.03609833, -0.03908775,
         0.01265476,  0.00910169, -0.01391762,  0.01885051,  0.01318571],
       [ 0.04953771,  0.0288942 , -0.0360706 ,  0.03609833, -0.03908775,
         0.01265476,  0.00910169, -0.01391762,  0.01885051,  0.01318571],
       [ 0.04953771,  0.0288942 , -0.0360706 ,  0.03609833, -0.03908775,
         0.01265476,  0.00910169, -0.01391762,  0.01885051,  0.01318571],
       [ 0.03670323,  0.03632064, -0.02155775, -0.00741614, -0.01344854,
         0.0231594 , -0.03701564,  0.01490154, -0.02217209, -0.00307537],
       [-0.00204311, -0.00258059, -0.01987265,  0.02261111,  0.02463872,
         0.02170874,  0.0444521 , -0.00680195, -0.03424485,  0.03863857],
       [ 0.00031151,  0.04823455, -0.01357142, -0.00505089, -0.04180221,
        -0.01350534, -0.0236349 , -0.0146823 

In [ ]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 51ms/step
[[[ 0.04953771  0.0288942  -0.0360706   0.03609833 -0.03908775
    0.01265476  0.00910169 -0.01391762  0.01885051  0.01318571]
  [ 0.04953771  0.0288942  -0.0360706   0.03609833 -0.03908775
    0.01265476  0.00910169 -0.01391762  0.01885051  0.01318571]
  [ 0.04953771  0.0288942  -0.0360706   0.03609833 -0.03908775
    0.01265476  0.00910169 -0.01391762  0.01885051  0.01318571]
  [ 0.04953771  0.0288942  -0.0360706   0.03609833 -0.03908775
    0.01265476  0.00910169 -0.01391762  0.01885051  0.01318571]
  [ 0.03670323  0.03632064 -0.02155775 -0.00741614 -0.01344854
    0.0231594  -0.03701564  0.01490154 -0.02217209 -0.00307537]
  [-0.00204311 -0.00258059 -0.01987265  0.02261111  0.02463872
    0.02170874  0.0444521  -0.00680195 -0.03424485  0.03863857]
  [ 0.00031151  0.04823455 -0.01357142 -0.00505089 -0.04180221
   -0.01350534 -0.0236349  -0.0146823   0.03655832  0.00349749]
  [-0.03438959  0.01031858  0.04086875  0.00886862 -0.03294

In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0, 479, 444,   5, 216], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 17ms/step
[[ 0.04953771  0.0288942  -0.0360706   0.03609833 -0.03908775  0.01265476
   0.00910169 -0.01391762  0.01885051  0.01318571]
 [ 0.04953771  0.0288942  -0.0360706   0.03609833 -0.03908775  0.01265476
   0.00910169 -0.01391762  0.01885051  0.01318571]
 [ 0.04953771  0.0288942  -0.0360706   0.03609833 -0.03908775  0.01265476
   0.00910169 -0.01391762  0.01885051  0.01318571]
 [ 0.04953771  0.0288942  -0.0360706   0.03609833 -0.03908775  0.01265476
   0.00910169 -0.01391762  0.01885051  0.01318571]
 [ 0.03670323  0.03632064 -0.02155775 -0.00741614 -0.01344854  0.0231594
  -0.03701564  0.01490154 -0.02217209 -0.00307537]
 [-0.00204311 -0.00258059 -0.01987265  0.02261111  0.02463872  0.02170874
   0.0444521  -0.00680195 -0.03424485  0.03863857]
 [ 0.00031151  0.04823455 -0.01357142 -0.00505089 -0.04180221 -0.01350534
  -0.0236349  -0.0146823   0.03655832  0.00349749]
 [-0.03438959  0.01031858  0.04086875  0.00886862 -0.03294997  0.02801647


In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [ ]:
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import plot_model
import numpy as np

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"]

# Vocabulary size and one-hot encoding
voc_size = 500
onehot_repr = [one_hot(words, voc_size) for words in sent]

# Padding sequences
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)

# Define and compile the model
dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

# Predict embeddings for the first embedded document
predictions = model.predict(embedded_docs[0].reshape(1, -1))
print(predictions)


1/1 [==============================] - 0s 130ms/step
[[[ 0.04155661 -0.03431118 -0.03092691  0.00692111 -0.00462176
   -0.01885381  0.02350387 -0.00883232  0.01638155 -0.01073293]
  [ 0.04155661 -0.03431118 -0.03092691  0.00692111 -0.00462176
   -0.01885381  0.02350387 -0.00883232  0.01638155 -0.01073293]
  [ 0.04896444 -0.03275836  0.04654919  0.02950792  0.02520351
    0.0189337   0.01031167 -0.03454479 -0.01223008  0.03624948]
  [ 0.03764815  0.0014595  -0.04438428  0.01678039  0.03300886
    0.03413651 -0.0124618  -0.00611252 -0.01241114 -0.03686144]
  [-0.01095581  0.03845438  0.04204661 -0.0302924  -0.04943941
    0.00162718  0.03080611  0.03627339 -0.04295382 -0.00394205]
  [-0.01739564 -0.02413379 -0.00771233 -0.02615061 -0.00811273
   -0.04569088 -0.04952872  0.04023388  0.00653907  0.00961218]
  [-0.00986443  0.01924405  0.0286277   0.02881862  0.00307324
    0.04910772  0.00291454  0.04728878 -0.00431604 -0.00474702]
  [ 0.00346109  0.04286821  0.01273472  0.00742247 -0.0246